spring.application.name: PIP
server.port: 8092
spring:
  datasource:
    url: jdbc:mysql://localhost:8306/PIP?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: csc1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect